version: '3.3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  # client:
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: react-container
  #   ports:
  #     - '3000:3000'
  #   stdin_open: true
  client:
    build: ./client
    ports:
      - "3000:3000"