version: '3.3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - '5000:5000'
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - '80:80'
    stdin_open: true