const Router = require('express')
const router = new Router()
const userController = require('../controllers/userController')
const authMiddleware = require('../middleware/authMiddleware')
const checkRole = require('../middleware/checkRoleMiddleware')

router.post('/signup', userController.registration)
router.post('/signin', userController.login)
router.get('/auth', authMiddleware, userController.check)
router.get('/users', userController.getAll)
router.get('/user/:id', userController.getOne)
router.get('/users_number', userController.getTotalNumberOfUsers)
router.get('/user_image/:id', userController.getUserImage)
router.get('/user_rating/:id', userController.getUserRating)
router.get('/filter', userController.getFiltered)
router.get('/verify/:id/:resetToken', userController.verify)
router.get('/reset_password/:userId/:resetToken', userController.resetTokenVerify)
router.post('/reset_password', userController.resetPassword)
router.post('/reset_user_password', userController.resetUserPassword)
router.patch('/update/:id', userController.update)
router.patch('/update_rating', userController.updateUserRating)
router.patch('/update_password/:id', userController.updatePassword)

module.exports = router