name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v1
      # - name: Create tar acrhive
      #   run: |
      #     mkdir ../publish
      #     cp -TR . ../publish
      #     tar -cf publish.tar ../publish/
      # - name: Copy files
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: "publish.tar"
      #     target: "~/"
      - name: Run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose down
            docker-compose up --build